---
- name: Install and run the application
  gather_facts: No
  hosts: centos_host

  tasks:
    - name: upgrade all yum packages
      yum:
        name: '*'
        state: latest

    - name: Install a list of yum packages
      yum:
        name:
          - yum-utils
          - epel-release
          - python-devel
          - device-mapper-persistent-data 
          - lvm2
          - git
        state: present

    - name: Install python pip 
      yum:
        name:
          - python-pip
        state: present

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    # - name: Check if Docker Compose is installed
    #   command: docker-compose --version
    #   register: docker_compose_check
    #   ignore_errors: yes

    - name: install docker compose
      shell: pip install docker-compose
      # when:
      #   - docker_compose_check.msg is defined
      #   - docker_compose_check.msg.find('No such file or directory') != -1
    
    - name: Get required repos from git
      git: repo=https://github.com/gauti038/3yournode-challenge.git dest=/app/

    - name: build the front-end image
      shell: docker build -t frontend-vue:test1 /app/frontend

    - name: build the backend-end image
      shell: docker build -t backend-django:test1 /app/backend
    
    - name: run the service defined by docker-compose.yml
      docker_service:
        project_src: /app/
        