---
- name: Install and run the application
  gather_facts: No
  hosts: centos_host

  tasks:
    - name: upgrade all yum packages
      yum:
        name: '*'
        state: latest

    - name: Install a list of yum packages
      yum:
        name:
          - yum-utils
          - epel-release
          - python-devel
          - device-mapper-persistent-data 
          - lvm2
          - git
        state: present

    - name: Install python pip 
      yum:
        name:
          - python-pip
        state: present

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: install docker compose
      shell: pip install docker-compose
    
    - name: Get required repos from git
      git: repo=https://github.com/gauti038/3yournode-challenge.git dest=/app/
    
    - name: run the service defined by docker-compose.yml
      docker_service:
        project_src: /app/
        